name: Build APK

on:
  push:
    branches:
      - main  # Replace with your branch if you use a different one (e.g., 'master')

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout code from GitHub
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify the Node.js version you want

      # Install dependencies (Capacitor and project dependencies)
      - name: Install dependencies
        run: |
          npm install
          npm install -g @capacitor/cli  # Install Capacitor globally

      # Sync Capacitor to update Android platform
      - name: Sync Capacitor
        run: npx cap sync

      # Build the APK using Gradle
      - name: Build APK
        run: |
          cd android
          ./gradlew assembleRelease

      # Upload the APK as an artifact for download
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk
