name: Build APK

on:
  push:
    branches:
      - main  # Replace with your branch if you use a different one (e.g., 'master')

permissions:
  contents: write
  id-token: write
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout code from GitHub
      - name: Checkout code
        uses: actions/checkout@v2

      # Verify that the repo files are properly checked out
      - name: List project files
        run: ls -R .

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify the Node.js version you want

      # Install dependencies (Capacitor and project dependencies)
      - name: Install dependencies
        run: |
          npm install
          npm install -g @capacitor/cli  # Install Capacitor globally

      # Sync Capacitor to update Android platform
      - name: Sync Capacitor
        run: npx cap sync

      # Build the APK using Gradle
      - name: Build APK
        run: |
          cd android
          ./gradlew assembleDebug --stacktrace

      # Verify that APK exists
      - name: Verify APK exists
        run: ls android/app/build/outputs/apk/debug/

      # Upload the APK as an artifact for download (using v2 to avoid v3 issues)
      # - name: Upload Debug APK
      #   uses: actions/upload-artifact@v3  # Switch to v2 to avoid issues with v3
      #   with:
      #     name: app-debug.apk
      #     path: android/app/build/outputs/apk/debug/app-debug.apk
